---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-es
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vikunja-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Vikunja
        VIKUNJA_SERVICE_JWTSECRET: "{{ .VIKUNJA_JWT_SECRET }}"
        VIKUNJA_MAILER_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        VIKUNJA_MAILER_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        # VIKUNJA_MAILER_FROMEMAIL:
        # Postgres Init
        POSTGRES_DB: "{{ .VIKUNJA_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .VIKUNJA_PG_PASS }}"
        POSTGRES_USER: "{{ .VIKUNJA_PG_USER }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        FROM_EMAIL: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
  dataFrom:
    - extract:
        key: vikunja
    - extract:
        key: cloudnative-pg
    - extract:
        key: external-smtp
