---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-outline
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-redis-lb
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-authelia
    - name: cluster-apps-minio
    # - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/media/outline/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: outline
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
