---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    worker:
      config:
        core:
          sources: ["custom", "pci", "usb"]
        sources:
          usb:
            deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
            deviceLabelFields: ["class", "vendor", "device"]
          custom:
            - name: "zwave"
              matchOn:
                - usbId:
                    class: ["ff"]
                    vendor: ["10c4"]
                    device: ["ea60"]
            - name: "zigbee"
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["1cf1"]
                    device: ["0030"]
            - name: "flirc"
              matchOn:
                - usbId:
                    class: ["03"]
                    vendor: ["20a0"]
                    device: ["0006"]
