---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # FreshRSS
        FR_DATABASE_USER: "{{ .FR_DATABASE_USER }}"
        FR_DATABASE_PASS: "{{ .FR_DATABASE_PASSWORD }}"
        FR_DATABASE_HOST: &dbhost "{{ .PG_RW_INTERNAL_HOST }}"
        FR_DATABASE_NAME: &dbname freshrss
        # FR_DATABASE_TYPE: postgres
        # FR_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}" # from authelia
        # Postgres Init
        POSTGRES_DB: *dbname
        POSTGRES_HOST: *dbhost
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: freshrss
    - extract:
        key: cloudnative-pg
