---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: media
spec:
  releaseName: freshrss
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: freshrss/freshrss
      tag: 1.22.1
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      CRON_MIN: "18,48"
      DOMAIN: "https://rss.${SECRET_DOMAIN}/"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          # nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          # nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "rss-box"
          hajimari.io/group: "FreshRSS"
        hosts:
          - host: &host "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secret: freshrss-tls

    persistence:
      config:
        enabled: true
        mountPath: /var/www/FreshRSS/data
        existingClaim: freshrss-pvc
        # skipuninstall: true
    podAnnotations:
      secret.reloader.stakater.com/reload: freshrss-secret
    #   backup.velero.io/backup-volumes: config
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
