---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: redis-lb-configmap
    files:
      - haproxy.cfg=./config/haproxy.cfg
configurations:
  - ./patches/kustomizeconfig.yaml
labels:
  - pairs:
      app.kubernetes.io/name: &app redis-lb
      app.kubernetes.io/instance: *app
      app.kubernetes.io/part-of: redis
