---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: glauth
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: glauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        server.toml: |
          debug = true
          [ldap]
              enabled = true
              listen = "0.0.0.0:389"
          [ldaps]
              enabled = false
          [api]
              enabled = true
              tls = false
              listen = "0.0.0.0:5555"
          [backend]
              datastore = "config"
              baseDN = "dc=home,dc=arpa"
        groups.toml: |
          [[groups]]
              name = "svcaccts"
              gidnumber = 6500
              [[groups.customattributes]]
                oidNumber = g1
          [[groups]]
              name = "admins"
              gidnumber = 6501
              [[groups.customattributes]]
                oidNumber = g2
          [[groups]]
              name = "people"
              gidnumber = 6502
              [[groups.customattributes]]
                oidNumber = g3
        # Create passbcrypt:
        #   https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)
        # or
        #   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
        users.toml: |
          [[users]]
              name = "{{ .search_username }}"
              uidnumber = 5000
              primarygroup = 6500
              passbcrypt = "{{ .search_passbcrypt }}"
              [[users.capabilities]]
                  action = "search"
                  object = "*"
              [[users.customattributes]]
                oidNumber = u1
          [[users]]
              name = "{{ .ben_username }}"
              mail = "{{ .ben_email }}"
              givenname = "{{ .ben_givenname }}"
              sn = "{{ .ben_surname }}"
              uidnumber = 5001
              primarygroup = 6502
              othergroups = [ 6501 ]
              passbcrypt = "{{ .ben_passbcrypt }}"
              [[users.customattributes]]
                oidNumber = u2
  dataFrom:
    - extract:
        key: glauth
