---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kutt
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-redis-lb
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-ingress-nginx
  path: ./kubernetes/apps/default/kutt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kutt
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
