---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp-es
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: headlamp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Authelia
        OAUTH_SECRET: "{{ .HEADLAMP_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: authelia
