---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: security
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.7@sha256:e5f5011ce7f20c721eda0876ccd9a023d315237d197aaf311269da424b9c6997
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: AUTHELIA_STORAGE_POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: AUTHELIA_STORAGE_POSTGRES_DATABASE
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: POSTGRES_SUPER_PASS
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: AUTHELIA_STORAGE_POSTGRES_USERNAME
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: AUTHELIA_STORAGE_POSTGRES_PASSWORD
