---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.11.1@sha256:e33c472d1b2ee30604d081b8043755c36a9d6474c1f49adbe65a1e75874561b3
    env:
      TZ: America/New_York
      UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local
      UN_SONARR_0_PATHS_0: /nfs/complete/sonarr
      UN_SONARR_0_API_KEY:
        valueFrom:
          secretKeyRef:
            name: sonarr-secret
            key: SONARR__API_KEY
      UN_RADARR_0_URL: http://radarr.media.svc.cluster.local
      UN_RADARR_0_PATHS_0: /nfs/complete/radarr
      UN_RADARR_0_API_KEY:
        valueFrom:
          secretKeyRef:
            name: radarr-secret
            key: RADARR__API_KEY
      # UN_LIDARR_0_URL: http://lidarr.media.svc.cluster.local
      # UN_LIDARR_0_PATHS_0: /nfs/complete/lidarr
      # UN_LIDARR_0_API_KEY:
      #   valueFrom:
      #     secretKeyRef:
      #       name: lidarr-secret
      #       key: LIDARR__API_KEY
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 1100
      runAsGroup: 1100
      fsGroup: 1100
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 1111
    podAnnotations:
      secret.reloader.stakater.com/reload: |-
        radarr-secret,sonarr-secret
    persistence:
      complete:
        enabled: true
        existingClaim: unpackerr-complete-nfs-pvc
        mountPath: /complete
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1000Mi
