---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
labels:
  - pairs:
      app.kubernetes.io/name: unpackerr
      app.kubernetes.io/instance: unpackerr
