---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unpackerr-complete-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: unpackerr-complete-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_BASE_PATH}/swap/downloads/completed
  mountOptions: ["nfsvers=3", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unpackerr-complete-nfs-pvc
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: unpackerr-complete-nfs
  resources:
    requests:
      storage: 1Mi
