---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-home-assistant-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-rook-ceph-cluster
    # - name: cluster-apps-volsync-app
  path: ./kubernetes/apps/home-automation/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant
      namespace: home-automation
  interval: 30m
  retryInterval: 1m
  timeout: 3m
