---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  values:
    nextcloud:
      initContainers:
        init-db:
          image: ghcr.io/onedr0p/postgres-initdb:14.6
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nextcloud-secret
