---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  values:
    nextcloud:
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-initdb:14.7
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nextcloud-secret
