---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghost-es
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ghost-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GHOST_DB_USER: "{{ .GHOST_DB_USER }}"
        GHOST_DB_PASS: "{{ .GHOST_DB_PASS }}"
        GHOST_DB_DB: "{{ .GHOST_DB_DB }}"
        GHOST_USER: "{{ .GHOST_USER }}"
        GHOST_PASS: "{{ .GHOST_PASS }}"
        GHOST_EMAIL: "{{ .GHOST_EMAIL }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
  dataFrom:
    - extract:
        key: external-smtp
    - extract:
        key: ghost
