---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  # FIXME Upgrade failed
  interval: 5m

  chart:
    spec:
      # renovate: registryUrl=https://charts.visonneau.fr
      chart: tailscale-relay
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: mvisonneau
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: docker.io/mvisonneau/tailscale
      tag: 'v1.48.2'
    config:
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "10.42.0.0/16,10.43.0.0/16,10.69.10.0/24,192.168.1.0/24,192.168.2.0/24"

  valuesFrom:
    - kind: Secret
      name: tailscale-secret
      valuesKey: TS_AUTHKEY
      targetPath: config.authKey
