---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./audiobookshelf/ks.yaml
  # - ./bazarr/ks.yaml
  # - ./calibre/ks.yaml
  # - ./calibre-web/ks.yaml
  - ./freshrss/ks.yaml
  # - ./overseerr/ks.yaml
  - ./paperless/ks.yaml
  # - ./plex/ks.yaml
  # - ./prowlarr/ks.yaml
  # - ./podgrab/ks.yaml
  # - ./qbittorrent/ks.yaml
  # - ./radarr/ks.yaml
  # - ./readarr/ks.yaml
  # - ./recyclarr/ks.yaml
  # - ./sabnzbd/ks.yaml
  # - ./sonarr/ks.yaml
  # - ./tautulli/ks.yaml
  # - ./unpackerr/ks.yaml
  - ./wikijs/ks.yaml
