---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./bazarr/ks.yaml
  - ./freshrss/ks.yaml
  # - ./ombi/ks.yaml
  - ./overseerr/ks.yaml
  - ./paperless/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./wikijs/ks.yaml
