---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: authentik-redis
  app.kubernetes.io/instance: authentik
