---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-gitea
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/default/gitea/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-authelia
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-minio
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gitea
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
