---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr-books
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/readarr-develop
      tag: 0.1.7.1882@sha256:f16ed82e04df9c04d864bccbab20b0afb7041bfbbbe7f1089a6b9cfab2c8a015

    podAnnotations:
      secret.reloader.stakater.com/reload: &secret readarr-books-secret

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 1111
        - 1100

    env:
      READARR__INSTANCE_NAME: Readarr Books
      READARR__PORT: &port 8787
      READARR__APPLICATION_URL: "https://readarr-books.${SECRET_DOMAIN}"
      READARR__LOG_LEVEL: info
      READARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: READARR_BOOKS_API_KEY

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.bjw-s.dev/css/base/readarr/space-gray.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "readarr-books.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: readarr-books-config-pvc
        mountPath: /config

      media:
        enabled: true
        existingClaim: readarr-books-nfs-pvc
        mountPath: /nfs/media

      ingress:
        enabled: true
        existingClaim: readarr-books-download-nfs-pvc
        mountPath: /nfs/complete

    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 4069M
