apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-books-download-nfs
spec:
  storageClassName: readarr-books-download-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_BASE_PATH}/swap/downloads/completed
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=3", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-books-download-nfs-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name readarr-books
    app.kubernetes.io/instance: *name
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: readarr-books-download-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-books-nfs
spec:
  storageClassName: readarr-books-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_BASE_PATH}/media/documents/books
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=3", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-books-nfs-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name readarr-books
    app.kubernetes.io/instance: *name
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: readarr-books-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-books-config-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name readarr-books
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
