---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./nfs-pvc.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: &app minio
      app.kubernetes.io/instance: *app
