---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./op-minio-secret.yaml
  - ./nfs-pvc.yaml
  - ./helmrelease.yaml
