---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: minio-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.9
    path: /volume1/kubernetes/apps/minio
  mountOptions: ["nfsvers=3"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 1Mi
