---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: op-minio-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, MINIO_PROMETHEUS_TOKEN
        key: minio
