---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kured-es
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kured-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DISCORD_WEBHOOK_URL: "{{ .KURED_DISCORD_WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: kured
