---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-es
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # N8N
        N8N_POSTGRES_URL: "postgresql://{{ .N8N_PG_USER }}:{{ .N8N_PG_PASS }}@{{ .PG_RW_INTERNAL_HOST }}/{{ .N8N_PG_DB }}"
        # Postgres Init
        POSTGRES_DB: "{{ .N8N_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_PORT: "{{ .PG_PORT }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .N8N_PG_USER }}"
        POSTGRES_PASS: "{{ .N8N_PG_PASS }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        FROM_EMAIL: "N8N <{{ .EXTERNAL_SMTP_FROM_EMAIL }}>"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
    - extract:
        key: external-smtp
