---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app n8n
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/n8n-io/n8n
      tag: 0.231.0

    command: ["n8n"]

    env:
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      N8N_HOST: &host n8n.${SECRET_DOMAIN}
      N8N_EDITOR_BASE_URL: "https://n8n.${SECRET_DOMAIN}/"
      WEBHOOK_URL: "https://n8n.${SECRET_DOMAIN}/"
      N8N_PORT: &port 80
      N8N_PROTOCOL: https
      N8N_USER_FOLDER: /config
      N8N_METRICS: true
      N8N_EMAIL_MODE: smtp
      N8N_SMTP_HOST:
        valueFrom:
          secretKeyRef:
            name: &secret n8n-secret
            key: SMTP_HOST
      N8N_SMTP_PORT:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: SMTP_PORT
      N8N_SMTP_USER:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: SMTP_USER
      N8N_SMTP_PASS:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: SMTP_PASS
      N8N_SMTP_SENDER:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: FROM_EMAIL
      N8N_SMTP_SSL: "false"
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: POSTGRES_HOST
      DB_POSTGRESDB_PORT:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: POSTGRES_PORT
      DB_POSTGRESDB_DATABASE:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: POSTGRES_DB
      DB_POSTGRESDB_USER:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: POSTGRES_USER
      DB_POSTGRESDB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: *secret
            key: POSTGRES_PASS
      QUEUE_BULL_REDIS_HOST: n8n-redis.default.svc.cluster.local

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:workflow
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: n8n-config-pvc

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    resources:
      requests:
        cpu: 10m
        memory: 200Mi
      limits:
        memory: 1000Mi
