---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app app_name
  namespace: namespace_name
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  values:
    global:
      nameOverride: *app

    image:
      repository: var_repo
      tag: var_tag

    service:
      main:
        ports:
          http:
            port: &port var_port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: var_haji_icon
        hosts:
          - host: &host "app_name.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
