---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        TS_AUTH_KEY: "{{ .TS_AUTHKEY }}"
  dataFrom:
    - extract:
        key: tailscale
