---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tailscale-gateway
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    serviceAccount:
      name: tailscale-sa

    image:
      repository: ghcr.io/tailscale/tailscale
      tag: v1.36.0@sha256:4b3c5149c22c827351c7daa01c1c1fdd6c3ca7e0ce592ec001f0e07729168442
    env:
      TZ: ${TIMEZONE}
      TS_KUBE_SECRET: tailscale-secret
      SA_NAME: tailscale-sa
      TS_USERSPACE: "true"
      TS_ROUTES: "10.42.0.0/16,10.43.0.0/16,10.69.0.0/16"
      TS_EXTRA_ARGS: "--advertise-exit-node"
    envFrom:
      - secretRef:
          name: tailscale-secret

    service:
      main:
        ports:
          http:
            port: &port 45387

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000

    ingress:
      main:
        enabled: false
