apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
    namespace: vpn
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:OLhjGBOqaGKRqpe3RsSQNnk0OKHTSqWZZC+ZL52g2Nkvsq4Ej9NnEJXAASItMzqYn4SW5U9ysfli,iv:vSLW15Bwjnqy49bObJoC9esd+F9gZR0K1H2mzsafZxI=,tag:6QthFqQGc/6oXa988sqF+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bklSRmgvTSt1ckpPcWRy
            T01mMU1HMlNuc1ZmWlVnOVpIM3dNeHNMSkZJCk5sQkJZYmZGV3pRbFZwMUdUU0VW
            Q3pvb1EyMkR3V211ZlFzNkJKMXdqNzgKLS0tIFo0RCtab2pEdExlSjlobnlicy9C
            YUl0ekQ4amt3NnMzSjB2M3J2ZzNMb3MK6oHw8RGAkBEHIpGLSFW95R0CC6kZn1c/
            tGnGc2h9mXTG7LVnaZ17HzBXAG7bNPPREw/8X3w7I03b4syxV7JGyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T15:52:34Z"
    mac: ENC[AES256_GCM,data:8J46SU2+jFhEdNGZ0S0ulnGO4/X/BoevNjo1dQccRnQUbzr0H/mGmnMczAoIvSB4xGLjbftnOwsl/3vdDpB8mP1ZDZ/Wh4rlUhOlQkdLw6C9A1JU2HAVGNs74/cVNoLRmDcl6ZYabBz8GzUPNM0TTk3HLtAd2qikg+k1Z4V0974=,iv:KaWkxhxo9F97/0NER/6eRu8n4UdV8qeZMMbeOxQzKV0=,tag:rVXglflNVQ6wG5YiHOfjQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
