---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shlink
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shlink-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # geolite
        GEOLITE_LICENSE_KEY: "{{ .GEOLITE_LICENSE_KEY }}"
        # Shlink
        DB_USER: &dbuser "{{ .SHLINK_PG_USER }}"
        DB_PASSWORD: &dbpass "{{ .SHLINK_PG_PASS }}"
        DB_DRIVER: postgres
        DB_HOST: &dbhost "{{ .PG_RW_INTERNAL_HOST }}"
        DB_NAME: &dbname "{{ .SHLINK_PG_DB }}"
        # Postgres Init
        POSTGRES_DB: *dbname
        POSTGRES_HOST: *dbhost
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: *dbpass
        POSTGRES_USER: *dbuser
  dataFrom:
    - extract:
        key: geolite
    - extract:
        key: shlink
    - extract:
        key: cloudnative-pg
