kind: ENC[AES256_GCM,data:jfUjSWWL,iv:Nk68D1EvCrRcPgfgO6BRDK7AlNdSmQKyxZDRfTLyzRc=,tag:5RRLcXwWXhIBwimGUin1AQ==,type:str]
ansible_user: ENC[AES256_GCM,data:gnqjVrGgEA==,iv:z7Oy+QfSX10EW0dqONVjpc4rqTde1xztqsZ4lHSG8b8=,tag:9zRpnBOk0puDa+tajV4luQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:f0SC6YP4+jinbg==,iv:Okq0pXnPD0WwOHw9I6Yfq6/gr0ezUi0aqJnIqGUbwJg=,tag:aQXgqvM/AoyPcyRxgmdPLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUDdGd0llVVV6WkFNajlS
            ZXdRMHZxM0t2Q1N0Z09nN1kxRnFJMWRIU2xrCmJxNkRWc2JXRWp0bktkRlJoZTlP
            YzNNL3lRTWF0L2pob2V5S3o5WUZGMTQKLS0tIDJRemJNQlRHNng5SUg4Z0lHZ1lz
            VmlWMmJxVVhsb2dCWTh3WWJzb1RqTk0KSRfgAboA5kuBJXtmTOzGygXUeAKOLjAD
            5c58zSVZOnDF+tt+eB8dIa256xt+8iDxP6c9hSSPvEzgfdXJIjPQhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T00:34:17Z"
    mac: ENC[AES256_GCM,data:c9V9Q5dGUaZozkYDbchfXhzEY3vwnQOiKFjNnQc1veCnj+ipel9/ezCzwR+bSTNf/DEJm3jiqKdMwT5hpQmFpjH9h97O+jai1KcfNhk0lWhHt5gfLrSa50hvGRMH5qHlWzsB0hJUeRO01ItZRZEJyFEeRjnM+ZkVPTFla3N7nc8=,iv:LZ977CeEZ3COgpVTSrat7fe6jAMea2xFMm/r/lfsJEk=,tag:1q9d99Nng1NmXbXaE0hyOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
