kind: ENC[AES256_GCM,data:PX9yrVl6,iv:FUHmIjfLUzCcL79DFol1lTbTTIeNbnKfLZ4sO2RsHhI=,tag:kfwQCqwVKlSiM2lUHRcoMA==,type:str]
ansible_user: ENC[AES256_GCM,data:8sMCYML+Zw==,iv:xD2Owa2aMEV5oP2NuOZkAgxiZ5K345u7HD5zuzYaAtM=,tag:CiftlEVm7978cEUDiwuOqQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aKg2QHTsgyCfKg==,iv:9woKsfIP/FT02Jhh1xdjrKPuHVCYX+V4mk4gaJnfsSU=,tag:/HsGtc6K2Nt8d0sqIj39zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTU13T0N4ZE5tcTJaTVZy
            QllqeU1NTk1zV2dTYm9QcGNEdkFzNVZ4ZXhBCjJwYkcvOE50U2FRcEJnUUNXSzI2
            YWFXV1ZteHlDSXZYQUJDeW0ybnhtcFEKLS0tIHNUa3VFVzJYdEJ4YUJkaUEydkVT
            b1VDVWp1WnFuWFVCemtHa3ZPa3hhOW8KIVVw8kcmyendmSuyWa1AtIHNt0ZhW0Q+
            dGRsP49gJhOp9KDcMaQRDFIfMsvi3EDOvyNv3EUksRdKewPT2riC6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T10:50:41Z"
    mac: ENC[AES256_GCM,data:jWixRdaEKvM791BvPgBezfzvu1RMNy6W7DFPlxZeR+xkJHeyNcFJE9+3jn3n+cdLSpEVQumnI3sYO3vHzeU/qA0PWyhZRokgtyze26LG7pB4s/wJu9xUVChMg+1BRYeUb3U2cMYDswI32EDIcyFpz3KF8xazIPWybuWzfVnD058=,iv:cEWSTyqm1bHbjGj6nhOYW5zPWuKfX64TTBOKdLvV5LE=,tag:0KmZDaVfHjLqAfqHWCJqCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
