kind: ENC[AES256_GCM,data:FVtguJDW,iv:wNqOWSPdXYdk7bDncDa0U/gZbUI7rge2fz5M9/Z99uw=,tag:t9i2cKE2LdjrbljgH5p1zg==,type:str]
ansible_user: ENC[AES256_GCM,data:qqxgbKvADg==,iv:UMA5rFPgq7vNFEW7BEsssNPiEMt3Irw13GUPpu/ftcw=,tag:oidZYoEELEp24gyOKE0esw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nfHqt/FvSrvVTg==,iv:Yf1Ayne5/b1h6ERSMm+qnC3rpy+QgIYvHEeF3CDLx88=,tag:pRVvEwlL8GXfoIAK1xoflQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZjNqNWkzQXY1cUc3NmhR
            QVZadnFJS0w1L1lQRjZXY2Iyd1piNlA1WVNJCnBhVHlMNmhtTGJmQWpKakh5dzZZ
            VUlCb3luYWFwWlF6R1ZXbitxdmErL2cKLS0tIG1kcVBDekRWZVg4c0J0T3JyWVhy
            UXJYNUJQU3M5ZXhRMURJTkY2U09zaDQKvb8OmjcmGJ6MxYZ6v5BOc0bgCsnSbP5J
            5IowjjUy6ewwJdAC0HnO0CUp2mTeAFITn26rkdfL//tjHZBRAQXydw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T11:54:45Z"
    mac: ENC[AES256_GCM,data:UkJYYvduqVmvh8KgwcHEhQRVfDd2BpP9l0KXjJxnhhkpxsaYg5+xENxEW6sa7AATLQ0SK3SBEzJb4zzkETAf/OCdRK2LAr3KMCsz7cKZcVxolPQeTvHnOQgeMXZ6F7tE+/MdsTjfO9SS8xpnu5YLQaP+VzE34oPJfxHFF/CspAQ=,iv:AicM4ouXTWc85YPMSXG3VZxH4ZYHudf4lepFKdVt2k8=,tag:RarHwqTxbrKFPdfsPI65fQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
