kind: ENC[AES256_GCM,data:G+wZ01nM,iv:xjh0Sr9d3WyWejjnLkGaJz+lNQ38y1/b1kTiIECVCPU=,tag:11qwbwwbb5HGyFXbU+MUiw==,type:str]
ansible_user: ENC[AES256_GCM,data:1ku8jv/WUg==,iv:HgfKjXpyamac0UWM9pnz4dtdLNjnrl0ntk6Mxjer0Mw=,tag:s1+HaPHjP7VPDCwSZXTw+Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:N92GerXdZhsKLg==,iv:cinPGjarQW2JTP3KlcPr92qvmGACsObj1+6fcmZV0mc=,tag:+RV2GNX20bmcCMDWG8qpBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MmR2SXNWb1JtYnpQRzdx
            QldzRFJybUtucXE3cGpHaXdjM3Fud1NjVmswCmZtWWt1TDNZWUtxcUp0eTRaeG9V
            KzFpOEgzV0ZqV2hDRzRHTEtMM2RwL3cKLS0tIElvOThJMWN3bnFEckVMbE0zZ2ZP
            QUc1WXRYc0NIdi9Xc2g4UGIyTEczQjgKmpPePUle4PfgTIQNK96M6tUgMmelrJFy
            dFtcdgHmSqimYxSoREiBw52rfbRJv3PY/JGqIDYaIRHXLqOMmwImQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T10:50:41Z"
    mac: ENC[AES256_GCM,data:e3boTllEKs2KvW87zB9LhM5fqO0LIflJ3bS+lGGUtc+jYuuvuVqRWq65IE4sS3d1rAdTpiFJnvqSt68Xjdls9p5CfwF1xkkSKZxg5WBhn3gxSv/nwxfow59DiTda3X8rvwxri9SPPJ217YrFF0LHJYAXp2xjEqXGAZru46hHU90=,iv:XXI4SJlFEWjVB2o1TO7wsB20JG8JXi765i0o+rxD2LM=,tag:DXT++9WGTGUFvWd1xYEpVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
