kind: ENC[AES256_GCM,data:kwvvo6qD,iv:QH4fXSl+XmfoCbGKFnJvZSrailyYQyjCnPrPZqBLBsU=,tag:1SHhaVsfcoZk7Q5ESerzfA==,type:str]
ansible_user: ENC[AES256_GCM,data:BaTWG2KLMA==,iv:Ek59V5xSFdtgucMiXqssEV3ajD7W28Jbo4mqXxmjTtI=,tag:fZf9zCcYOVitjPQGH3/eyg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:F40usclLXIQXlQ==,iv:043ytN9XcmGQxRAjgyM4bwPLNI/3enfA2UYR3WLGQ+M=,tag:fgPS70ErCRpijZ6ekmE/2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQWtRZzNnVnJ1M2pMRWdy
            Q1RCVm12dkJmbmN3TTd2blM2bGI3cGhnZUE0Ckx2czZNQ2FWRU5wbVJpYXFkRm4r
            ZVpUelEvNXYxS1Y4VE5nSGtHbXorWXcKLS0tIEc0UnF4Vm9KbTJtRHpldTBZVmsw
            SlpidTI2em5kbGtLYXp4NGZJNXVEUTAK35SOqQCY4IQTXmBgiP6Opu7kr4fFnTPX
            3opCuO2PvOhh0bz4j5NUuj6QSliWA/pgUVmUZSwepyuxWsiGmInIoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-18T18:58:42Z"
    mac: ENC[AES256_GCM,data:BDVPWnwsHSoHkxasCm+AnKQsavIcA34VHBt5yl5ghZYMRgSUBbWu/MnetYuVAdm2wr+Kyg+x0w5EERycMAqB/ogGwF9HAJLlP7Sjtdw9tqPuW9xZ3s3xBu40NIFsYG4sVHKR0qjptSqwTSRi0kOd2ikIm8zTN7vJaAJyDzGdnz8=,iv:ueBAcE/GsDETr5DQi9brhUe03feJVZezYwmuP/08meA=,tag:jOYf/+kW1XehYfME+g9NmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
