kind: ENC[AES256_GCM,data:T/KI2EZ2,iv:4aHW3XCdBOqqW3dmfrtWq/4j1+P7tJahEkHOu9lnVss=,tag:9xBGQ8XJkpact0p+qlBquQ==,type:str]
ansible_user: ENC[AES256_GCM,data:rfSslNDlig==,iv:sLkxgCcZH4Z+VLFQi1M3AcXpl5h3eGQ9YcYrt+jzUnI=,tag:qsLPNVVDXFzpuXmqW9RT9g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nfAOulpvtDz9ig==,iv:NPeLbH2czHYV7/GdONzh7hPctTnD3wNw9LcExLonBdE=,tag:4V60702bYk/QM6Ci7DWAzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SDZ3dkNCMm5RVlQ0RVdK
            dDNrTjZUdFdMalNLdHpzYWtySnFIUE51WVRnClVEdEx4aEMrQ29NNW44bktrUWJZ
            K0E1N2ZlK29uSnFnakxzTyswV3p3c3cKLS0tIHFyOTl0bEc1RUFIcE1OYWIwbDF3
            VUVUZTZrQ3o2eHEwM0pTbWZ4L3pXcFkKfEceLL68t4A2+cktWvMPcdOTzq5vkpz1
            +a2vHEsRO6TaVX4sdNLBvQfAfmiqrqy4oy5GoY4EWh4EYbyxBPNNOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T00:34:17Z"
    mac: ENC[AES256_GCM,data:Rff9qMlAuQzW1LQX1Urd2QfRV0uoQceoE3LoHDCqxmZ9tm9eBh7hqHuFRoMKicyjCwA2wTiCTzkx5HmyFJ2vh9rHLcvbcBDd/N5lchqbn1+OUS6rv3Gl9R+4JGaJcoi9p1Mw4PghomAJ5Sxe6RsTfDwo7IT/8aH+zVLp92yfxRQ=,iv:dITz3YAcV/TrfmNgox3pB+PWTDehwKB7+2sXwytdD6Y=,tag:oXlAQU2yYwOByLp+ESrSFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
