kind: ENC[AES256_GCM,data:VVF+npuv,iv:LSNfSDlr89ppiVPg5R2x77/dePqhcR9xNm67cWf9csM=,tag:NGqZVG0PH7GbWtSrro4QUw==,type:str]
ansible_user: ENC[AES256_GCM,data:IYbRx8wbcA==,iv:sR//qiELpv1J0v0RbMqskigHwD3s2KKVh+qS/I0KI5E=,tag:n01kz1Pw/xjoW/cUeQg+cg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:s2uf1oz3tEWlXQ==,iv:kqX+y3FbjLwvmdw6/Mu6u6YzUAY7TkD9ogMqa/QFNfc=,tag:ImK5TdFbb7kWI9140wnimA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RUJUcGhmVWl6YWxLZlFQ
            YldFUmExODdsdkM0dmpEam1EQVZxb3RjL2tNCnozSW1ZaHBYRTllVjRLUkk0c3JO
            TmQ4RG9mRzZvZnE4UkJxUzhJYTdZTGsKLS0tIE51WVV3bkY5UDhPbnI2NmUxeW9U
            SFZ5TmZ5UUs5dUUycEhQMFhDd1NIMVUKNQISmmaR2YusnGWhDRA/AU5KysBs/MI1
            bo6Lq1aNxYAwNsEjI+H4V6fRShoq8XXGGbvxoYPVFi3FNEEOult3+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-17T22:14:17Z"
    mac: ENC[AES256_GCM,data:5KqXR3Af9DpPYntwjr2Xfwe3bqP62ebDLmgbRszNQW2EYsRk4DODuyo7j+p8rwQWZfRPkKVIJrm4KKFWm+lV+bs7REkN0uxOh+NqnD8ySdm4W+aKOnlC3/beeZiCGqk9diiC8+aClvu2A8hwWWahG/62Ki6Gb2P557I2/RajUGE=,iv:oFYNMo5qqO1f5HqMEDYX8wKXW8lm8Xj3lr9WfKgyIh0=,tag:sMtVUIl/HTETdVJHBc2FmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
