kind: ENC[AES256_GCM,data:2LUitYwv,iv:te87UEy2H6qPVz95AegVIrbP4ZFPG42/QsddxVS/UyY=,tag:z9ufN7lL/0tiA1Bx8f54Zg==,type:str]
ansible_user: ENC[AES256_GCM,data:R/vDxa0z1g==,iv:vj13qezJTH9vd8TNE8OrzdlIb5PljAoIQo4S0pTiRio=,tag:r6oqvStXGScje54YfRD4/w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2XNQwwunBx7lcA==,iv:hxEoJG9HhI/fLonNLJ9+k8dBGj08By1LEQT2RrTaCQk=,tag:XDGqkNnK4YwOtu0DqQgUJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNy9WamxSMU1aTGxOUHNp
            MTIzY09POWhQN1NBVW16NVJkcDV1TEc5S2xvCmVPamZtV28zaWM3cFdOOVlQZnRz
            TjgrMjRydUdYbU5QNVBjOHMrSTFQbzAKLS0tIFBBK0NjbjFHYWVxZEVoOTQ5YXpF
            MFhWakZrRElYVEI5L01nMFJqNXlFNW8KC+jtRHbUAgRN9tyESjoHbJLRhgtirknH
            yGFLTFaThuXS6nMsSIsqJWRATxTT5Sy77EgpL/jT0HSaW9pMCVetrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T11:54:45Z"
    mac: ENC[AES256_GCM,data:eEyG84l+PBZShLjNrLs09xrqBnKSfUZCW4AJBupMVhtajTOKQrwp6JtDvPQYZD3XWsUN6be1Lpym0Ocv21Gy6JZtWDC6g5iSM5NmydkFa5aqT9SA8SMbj2m7cDorVi/XfS7ttqpmdHywDBN58c7Z2paNoMzT9LjCFmJRMVkXlew=,iv:VjOTFewMiBOBQaMJWE2QtPg4N2tS4x7HTDH6r6+AYmg=,tag:+wZwc4jiBf+3ynebRuhl/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
