---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-s3
  namespace: external-services
  annotations:
    external-dns.home.arpa/enabled: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  ingressClassName: nginx
  tls:
    - secretName: tls.nas-s3
      hosts:
        - "nas-s3.${SECRET_DOMAIN}"

  rules:
    - host: nas-s3.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas-s3
                port:
                  name: api
