---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./1password.yaml
  - ./actions-runner-controller.yaml
  - ./angelnu.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./flagger.yaml
  - ./grafana.yaml
  - ./gitea.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-at-home.yaml
  - ./k8s-gateway.yaml
  - ./kubereboot.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./mvisonneau.yaml
  - ./nextcloud.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./podinfo.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./traefik.yaml
  - ./weave-gitops.yaml
