---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 3.7.2@sha256:482afd4eb1d4167a23a1283cc5b08b442f37e384fe499c30aec0340007be8167
    env:
      TZ: ${TIMEZONE}
      SABNZBD__PORT: &port 80
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.media,
        sabnzbd.media.svc,
        sabnzbd.media.svc.cluster,
        sabnzbd.media.svc.cluster.local,
        sabnzbd.${SECRET_DOMAIN}
    envFrom:
      - secretRef:
          name: sabnzbd-secret
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
          # nginx.ingress.kubernetes.io/whitelist-source-range: |
          #   10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/icon: mdi:download
          hajimari.io/enable: "true"
        hosts:
          - host: &host "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1100
      runAsGroup: 1100
      fsGroup: 1100
      fsGroupChangePolicy: "OnRootMismatch"
      # supplementalGroups:
        # - 568
        # - 1111
        # - 65542
    # Note: If downloading very large nzbs it might be worth using NFS for your download directory.
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: sabnzbd-config-pvc
      blackhole:
        enabled: true
        existingClaim: sabnzbd-blackhole-nfs-pvc
        mountPath: /nfs/blackhole
      complete:
        enabled: true
        existingClaim: sabnzbd-downloads-complete-nfs-pvc
        mountPath: /nfs/complete
      incomplete:
        enabled: true
        existingClaim: sabnzbd-downloads-incomplete-nfs-pvc
        mountPath: /nfs/incomplete
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 6000Mi
