---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-es
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        nextcloud-username: "{{ .NC_USER }}"
        nextcloud-password: "{{ .NC_PASS }}"
        db-username: "{{ .NC_PG_USER }}"
        db-password: "{{ .NC_PG_PASS }}"
        # Postgres Init
        POSTGRES_DB: "{{ .NC_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_PORT: "{{ .PG_PORT }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .NC_PG_USER }}"
        POSTGRES_PASS: "{{ .NC_PG_PASS }}"
        POSTGRES_URL_STRING: "{{ .PG_RW_INTERNAL_HOST }}:{{ .PG_PORT }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        smtp-username: "{{ .EXTERNAL_SMTP_USER }}"
        smtp-password: "{{ .EXTERNAL_SMTP_PASS }}"
        FROM_EMAIL: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cloudnative-pg
    - extract:
        key: external-smtp
