---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 3.4.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: redis-lb.storage.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: "6379"
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
      host: &host cloud.${SECRET_DOMAIN}
      # mail:
      #   enabled: true
      #   fromAddress: hello
      #   domain: ${SECRET_PUBLIC_DOMAIN}
      #   smtp:
      #     authtype: NONE
      securityContext:
        runAsUser: 1100
        runAsGroup: 1100
      podSecurityContext:
        runAsUser: 1100
        runAsGroup: 1100

    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres-rw.storage.svc.cluster.local:5432
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      existingClaim: nextcloud-pvc
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-nfs-pvc
        accessMode: ReadWriteMany

  valuesFrom:
    # - targetPath: nextcloud.username
    #   kind: Secret
    #   name: &secret nextcloud-secret
    #   valuesKey: NEXTCLOUD_USER
    # - targetPath: nextcloud.password
    #   kind: Secret
    #   name: *secret
    #   valuesKey: NEXTCLOUD_PASS
    # - targetPath: externalDatabase.database
    #   kind: Secret
    #   name: *secret
    #   valuesKey: POSTGRES_DB
    # - targetPath: externalDatabase.host
    #   kind: Secret
    #   name: *secret
    #   valuesKey: POSTGRES_URL_STRING
    # - targetPath: externalDatabase.user
    #   kind: Secret
    #   name: *secret
    #   valuesKey: POSTGRES_USER
    # - targetPath: externalDatabase.password
    #   kind: Secret
    #   name: *secret
    #   valuesKey: POSTGRES_PASS
    # - targetPath: mail.smtp.host
    #   kind: Secret
    #   name: &secret nextcloud-secret
    #   valuesKey: SMTP_HOST
    # - targetPath: mail.smtp.port
    #   kind: Secret
    #   name: *secret
    #   valuesKey: SMTP_PORT
    # - targetPath: mail.smtp.name
    #   kind: Secret
    #   name: *secret
    #   valuesKey: SMTP_USER
    # - targetPath: mail.smtp.password
    #   kind: Secret
    #   name: *secret
    #   valuesKey: SMTP_PASS
