---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.12.2@sha256:4df605e37c63fbf9d602f22e87a4e5675bba15a8f41681350ff5c036e754dd6c

    service:
      main:
        ports:
          http:
            port: 8181

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        # annotations:
        #   nginx.ingress.kubernetes.io/configuration-snippet: |
        #     proxy_set_header Accept-Encoding "";
        #     sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.bjw-s.dev/css/base/tautulli/nord.css"></head>';
        #     sub_filter_once on;
        hosts:
          - host: &host tautulli.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config-pvc

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 500Mi
