---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  values:
    additionalContainers:
      exporter:
        name: exporter
        image: docker.io/kpetrem/mqtt-exporter:latest@sha256:9098d1cc5b357f44ae2da72833a1eb349330dbcbb27f7c06012bace9d93c8af1
        env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: LOG_MQTT_MESSAGE
            value: "True"
          - name: MQTT_ADDRESS
            value: emqx.home-automation.svc.cluster.local
          - name: MQTT_TOPIC
            value: "zigbee2mqtt/#"
          - name: MQTT_V5_PROTOCOL
            value: "True"
          - name: MQTT_USERNAME
            valueFrom:
              secretKeyRef:
                name: zigbee2mqtt-secret
                key: MQTT_USER
          - name: MQTT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zigbee2mqtt-secret
                key: MQTT_PASS
          - name: PROMETHEUS_PORT
            value: "80"
          - name: PROMETHEUS_PREFIX
            value: zigbee2mqtt_
          - name: ZIGBEE2MQTT_AVAILABILITY
            value: "True"
