---
version: "3"

includes:
  del: crud/delete.yaml

tasks:
  verify:
    desc: Verify flux meets the prerequisites
    cmds:
      - flux check --pre

  recon:
    desc: Force update Flux to pull in changes from your Git repository
    cmds:
      - flux reconcile -n flux-system source git home-kubernetes
      - flux reconcile -n flux-system kustomization cluster
