---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        # PAPERLESS_DARKSKY_API_KEY: "{{ .PAPERLESS_DARKSKY_API_KEY }}"
        # PAPERLESS_ECOBEE_API_KEY: "{{ .PAPERLESS_ECOBEE_API_KEY }}"
        PAPERLESS_ELEVATION: "{{ .PAPERLESS_ELEVATION }}"
        SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_MAIL: "{{ .PAPERLESS_ADMIN_MAIL }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        # PAPERLESS_GOOGLE_PROJECT_ID: "{{ .PAPERLESS_GOOGLE_PROJECT_ID }}"
        # PAPERLESS_GOOGLE_SECURE_DEVICES_PIN: "{{ .PAPERLESS_GOOGLE_SECURE_DEVICES_PIN }}"
        PAPERLESS_LATITUDE: "{{ .PAPERLESS_LATITUDE }}"
        PAPERLESS_LONGITUDE: "{{ .PAPERLESS_LONGITUDE }}"
        PAPERLESS_POSTGRES_URL: "postgresql://{{ .PAPERLESS_PG_USER }}:{{ .PAPERLESS_PG_PASS }}@{{ .PG_RW_INTERNAL_HOST }}/{{ .PAPERLESS_PG_DB }}"
        # Postgres Init
        POSTGRES_DB: "{{ .PAPERLESS_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_PORT: "{{ .PG_PORT }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .PAPERLESS_PG_USER }}"
        POSTGRES_PASS: "{{ .PAPERLESS_PG_PASS }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        # NFS
        NFS_SRV_HOST: "{{ .NFS_SRV_HOST }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg
    - extract:
        key: external-smtp
    - extract:
        key: nfs-server
