---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Paperless
        SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_MAIL: "{{ .PAPERLESS_ADMIN_MAIL }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        # Postgres Init
        POSTGRES_DB: "{{ .PAPERLESS_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_PORT: "{{ .PG_PORT }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .PAPERLESS_PG_USER }}"
        POSTGRES_PASS: "{{ .PAPERLESS_PG_PASS }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg
