---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./volsync.yaml
patchesStrategicMerge:
  - ./patches/postgres.yaml
commonLabels:
  app.kubernetes.io/name: paperless
  app.kubernetes.io/instance: paperless
