apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:W3n9RUhVli0cSMV9trp07tae9GWaVz4Ej1O5iu09g3RDFOXBgKp8CA==,iv:/iYh7tLlWGPVxrCBseuhWehWM57e92BOy3LXSWbEveQ=,tag:UzM6O2vMFKk10Z1jYIRLAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbFBQejJ3N3BsZmZ4bmIy
            QnJ0MUtEZDlRMnhHQkc1QjRDbHVPMW5lUEhNCnl6Z3FBUWYrVGFEMkNGZHI5Ymhw
            S1NpWDBWbllEYjhScW4wcDJkSGE1QVUKLS0tIG5BcENNSm9VMFQzbU16UFhQcW1R
            clNJQUYwRVAvK2o1aDRNVHN4aDQ4WHMKD9xibd5sA9VY/raqT3oOCUxgRWu7owIr
            YBJDMyZtdlTYs1ya+dY47IiubXEDSIykPn3JszKi6Pm0ztAL62YiBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T10:50:41Z"
    mac: ENC[AES256_GCM,data:BMTzigu4sMf4LnV9GpKOC1dmzAFJzDoyzha6YjJxfoNb2Opvaw0LKHkQRWgjxGmn7CbZBxHxM1rSiYt5UFuGBNAfsm9kujfUqe6OA+ABlraRJU5RUf7KuOpWr7T42WI/iOw5xL34jxvbSqSINjfnjb25cZ+4qJ9dl6wghfdKP5U=,iv:+gS/LgEGZl6b1zp/+l5QCXooRZJq68KshyipHWAJUa0=,tag:OhUH1FycpvlBM+k5xOi2dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
