---
kubernetes:
  children:
    master:
      hosts:
        k8s-main-0:
          ansible_host: 10.69.10.6
        k8s-main-1:
          ansible_host: 10.69.10.8
        k8s-main-2:
          ansible_host: 10.69.10.9
