---
kubernetes:
  children:
    master:
      hosts:
        in-nuc-1-main:
          ansible_host: 10.69.10.20
        in-nuc-2-main:
          ansible_host: 10.69.10.21
        in-nuc-3-main:
          ansible_host: 10.69.10.22
    worker:
      hosts:
        lv-m900-1-node:
          ansible_host: 10.69.10.30
        lv-m900-2-node:
          ansible_host: 10.69.10.31
