---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  exclusionList:
    - "error.*lookup github\\.com"
  suspend: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      namespace: 'actions-runner-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'cert-manager'
      name: '*'
    - kind: HelmRelease
      namespace: 'default'
      name: '*'
    - kind: HelmRelease
      namespace: 'logs'
      name: '*'
    - kind: HelmRelease
      namespace: 'home-automation'
      name: '*'
    - kind: HelmRelease
      namespace: 'kube-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'media'
      name: '*'
    - kind: HelmRelease
      namespace: 'monitoring'
      name: '*'
    - kind: HelmRelease
      namespace: 'rook-ceph'
      name: '*'
    - kind: HelmRelease
      namespace: 'security'
      name: '*'
    - kind: HelmRelease
      namespace: 'storage'
      name: '*'
  suspend: false
