---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-discord
  namespace: flux-system
spec:
  type: discord
  username: Flux
  channel: home-ops
  secretRef:
    name: flux-webhook-discord-secret
