---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-config
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-config-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Gitea
        adminPassword: "{{ .GITEA_ADMIN_PASSWORD }}"
        minioAccessKeyId: "{{ .MINIO_HOME_ACCESS_KEY }}"
        minioSecretAccessKey: "{{ .MINIO_HOME_SECRET_KEY }}"
        # bindDn: "{{ .LDAP_BIND_DN }}"
        # bindPassword: "{{ .LDAP_BIND_PASSWORD }}"
        # Minio
        minioEndpoint: minio.storage.svc.cluster.local:9000
        # Authelia
        key: gitea
        secret: "{{ .GITEA_OAUTH_CLIENT_SECRET }}"
        # CNPG
        POSTGRES_DB: gitea
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_USER: "{{ .GITEA_STORAGE_POSTGRES_USERNAME }}"
        POSTGRES_PASS: "{{ .GITEA_STORAGE_POSTGRES_PASSWORD }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: gitea
    - extract:
        key: minio
    - extract:
        key: cloudnative-pg
    - extract:
        key: external-smtp
