---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app gitea
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: gitea
      version: 7.0.2
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    statefulset:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      rootless: true
    containerSecurityContext:
      capabilities:
        add: ["SYS_CHROOT"]
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host gitea.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    memcached:
      enabled: false
    postgresql:
      enabled: false
    persistence:
      enabled: true
      accessModes: ["ReadWriteOnce"]
      size: 10Gi
      storageClass: ceph-block
    gitea:
      admin:
        email: admin@${SECRET_PUBLIC_DOMAIN}
        username: gitea
      config:
        APP_NAME: Tea, Git, Hot
        server:
          DISABLE_SSH: true
          DOMAIN: *host
          ROOT_URL: https://gitea.${SECRET_DOMAIN}
          ENABLE_GZIP: true
          LANDING_PAGE: login
          LFS_START_SERVER: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        ui:
          DEFAULT_THEME: arc-green
        repository:
          DEFAULT_BRANCH: main
          DEFAULT_PRIVATE: true
        database:
          DB_TYPE: sqlite3
          # DB_TYPE: postgres
        service:
          DISABLE_REGISTRATION: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          SHOW_REGISTRATION_BUTTON: false
          REQUIRE_SIGNIN_VIEW: true
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          DEFAULT_ALLOW_CREATE_ORGANIZATION: false
          DEFAULT_USER_IS_RESTRICTED: true
        cron:
          ENABLED: true
        attachment:
          STORAGE_TYPE: minio
          MINIO_BUCKET: *app
        storage:
          STORAGE_TYPE: minio
          MINIO_BUCKET: *app
        mailer:
          ENABLED: true
          MAILER_TYPE: smtp
          FROM: "Admin <admin@${SECRET_PUBLIC_DOMAIN}>"
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: true
          WHITELISTED_URIS: auth.${SECRET_DOMAIN}
      oauth:
        - name: authelia
          existingSecret: gitea-config-secret
          provider: openidConnect
          autoDiscoverUrl: https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration
          groupClaimName: groups
          adminGroup: admins
          restrictedGroup: people
      # ldap:
      #   - name: glauth
      #     existingSecret: gitea-config-secret
      #     securityProtocol: unencrypted
      #     host: glauth.default.svc.cluster.local
      #     port: "389"
      #     userSearchBase: ou=people,dc=home,dc=arpa
      #     userFilter: (&(objectClass=posixAccount)(|(uid=%[1]s)(mail=%[1]s)))
      #     adminFilter: (memberOf=ou=admins,ou=groups,dc=home,dc=arpa)
      #     emailAttribute: mail
      #     usernameAttribute: uid
      #     firstnameAttribute: givenname
      #     surnameAttribute: sn
      #     publicSSHKeyAttribute: publicSSHKey
      #     synchronizeUsers: "true"
      #     attributesInBind: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
  valuesFrom:
    - targetPath: gitea.admin.password
      kind: Secret
      name: gitea-config-secret
      valuesKey: adminPassword

    - targetPath: gitea.config.attachment.MINIO_ACCESS_KEY_ID
      kind: Secret
      name: gitea-config-secret
      valuesKey: minioAccessKeyId
    - targetPath: gitea.config.attachment.MINIO_SECRET_ACCESS_KEY
      kind: Secret
      name: gitea-config-secret
      valuesKey: minioSecretAccessKey
    - targetPath: gitea.config.attachment.MINIO_ENDPOINT
      kind: Secret
      name: gitea-config-secret
      valuesKey: minioEndpoint
    - targetPath: gitea.config.storage.MINIO_ACCESS_KEY_ID
      kind: Secret
      name: gitea-config-secret
      valuesKey: minioAccessKeyId
    - targetPath: gitea.config.storage.MINIO_SECRET_ACCESS_KEY
      kind: Secret
      name: gitea-config-secret
      valuesKey: minioSecretAccessKey
    - targetPath: gitea.config.storage.MINIO_ENDPOINT
      kind: Secret
      name: gitea-config-secret
      valuesKey: minioEndpoint

    # - targetPath: gitea.config.database.HOST
    #   kind: Secret
    #   name: gitea-config-secret
    #   valuesKey: POSTGRES_HOST
    # - targetPath: gitea.config.database.NAME
    #   kind: Secret
    #   name: gitea-config-secret
    #   valuesKey: POSTGRES_DB
    # - targetPath: gitea.config.database.USER
    #   kind: Secret
    #   name: gitea-config-secret
    #   valuesKey: POSTGRES_USER
    # - targetPath: gitea.config.database.PASSWD
    #   kind: Secret
    #   name: gitea-config-secret
    #   valuesKey: POSTGRES_PASS

    - targetPath: gitea.config.mailer.SMTP_ADDR
      kind: Secret
      name: gitea-config-secret
      valuesKey: SMTP_HOST
    - targetPath: gitea.config.mailer.SMTP_PORT
      kind: Secret
      name: gitea-config-secret
      valuesKey: SMTP_PORT
    - targetPath: gitea.config.mailer.USER
      kind: Secret
      name: gitea-config-secret
      valuesKey: SMTP_USER
    - targetPath: gitea.config.mailer.PASSWD
      kind: Secret
      name: gitea-config-secret
      valuesKey: SMTP_PASS
