---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
      rollingUpdate:
        surge: 1

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    podAnnotations:
      configmap.reloader.stakater.com/reload: &cm authelia-configmap
      secret.reloader.stakater.com/reload: &es authelia-secret

    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.37.5

    # args: ["--config", "/config/configuration.yml", "--config.experimental.filters", "expand-env"]

    enableServiceLinks: false

    envFrom:
      - secretRef:
          name: *es

    service:
      main:
        ports:
          http:
            port: 9091
          metrics:
            enabled: true
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          # cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
        hosts:
          - host: &host "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: *cm
        subPath: configuration.yml
        mountPath: /config/configuration.yml
        readOnly: false

    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 250Mi

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
