---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghost-db-es
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ghost-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GHOST_DB_ROOT_PASS: "{{ .GHOST_DB_ROOT_PASS }}"
        GHOST_DB_USER: "{{ .GHOST_DB_USER }}"
        GHOST_DB_PASS: "{{ .GHOST_DB_PASS }}"
        GHOST_DB_DB: "{{ .GHOST_DB_DB }}"
  dataFrom:
    - extract:
        key: ghost
