---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost-db
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 11.4.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    persistence:
      existingClaim: ghost-db-pvc

  valuesFrom:
    - targetPath: auth.rootPassword
      kind: Secret
      name: ghost-db-secret
      valuesKey: GHOST_DB_ROOT_PASS
    - targetPath: auth.username
      kind: Secret
      name: ghost-db-secret
      valuesKey: GHOST_DB_USER
    - targetPath: auth.password
      kind: Secret
      name: ghost-db-secret
      valuesKey: GHOST_DB_PASS
    - targetPath: auth.database
      kind: Secret
      name: ghost-db-secret
      valuesKey: GHOST_DB_DB
