---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ceph-block"
  resources:
    requests:
      storage: 10Gi
