---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/advplyr/audiobookshelf
      tag: 2.2.22
    env:
      TZ: ${TIMEZONE}
      AUDIOBOOKSHELF_UID: 1100
      AUDIOBOOKSHELF_GID: 1100
      CONFIG_PATH: /config
      METADATA_PATH: /config/metadata
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # nginx.ingress.kubernetes.io/whitelist-source-range: |
            # 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:podcast
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1100
      runAsGroup: 1100
      fsGroup: 1100
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 10000
        - 568
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
    persistence:
      audiobooks:
        enabled: true
        existingClaim: audiobookshelf-books-nfs-pvc
        mountPath: /audiobooks
        readOnly: true
      podcasts:
        enabled: true
        existingClaim: audiobookshelf-podcasts-nfs-pvc
        mountPath: /podcasts
        readOnly: true
      cache:
        enabled: true
        mountPath: /.npm
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
