---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-nfs
spec:
  storageClassName: audiobookshelf-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadOnlyMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: pelican.grz.bear
    path: /mnt/ingot/hydra/media/audio/audiobooks
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-nfs-pvc
  namespace: media
spec:
  accessModes: ["ReadOnlyMany"]
  storageClassName: audiobookshelf-nfs
  resources:
    requests:
      storage: 1Mi
