# https://github.com/advplyr/audiobookshelf
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podgrab
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/akhilrex/podgrab
      tag: latest
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: 8080

    podSecurityContext:
      runAsUser: 1111
      runAsGroup: 1111
      fsGroup: 1111
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 10000

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
    persistence:
      # config:
      #   enabled: true
      #   existingClaim: appdata
      #   mountPath: /config
      #   subPath: podgrab
      media:
        enabled: true
        existingClaim: podgrab-nfs-pvc
        mountPath: /assets
        # subPath: library/podcasts
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # auth.home.arpa/enabled: "true"
          # external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: podcast
        hosts:
          - host: &host podcasts.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
