---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-blackhole-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-blackhole-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_BASE_PATH}/swap/blackhole/torrent
  mountOptions: ["nfsvers=3", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-blackhole-nfs-pvc
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-blackhole-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-complete-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-downloads-complete-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_BASE_PATH}/swap/downloads/completed
  mountOptions: ["nfsvers=3", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-complete-nfs-pvc
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-downloads-complete-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-seeding-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-seeding-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_BASE_PATH}/swap/seeding
  mountOptions: ["nfsvers=3", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-seeding-nfs-pvc
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-seeding-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-incomplete-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-downloads-incomplete-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: ${SECRET_NFS_BASE_PATH}/swap/downloads/incomplete
  mountOptions: ["nfsvers=3", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-incomplete-nfs-pvc
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: qbittorrent-downloads-incomplete-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name qbittorrent
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 2Gi
