---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./grafana/ks.yaml
  - ./goldlocks/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./loki/ks.yaml
  - ./thanos/ks.yaml
  - ./vpa/ks.yaml
