---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR_BASE_URL: "http://{{ .RADARR_HOST }}:{{ .RADARR_PORT }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR_BASE_URL: "http://{{ .SONARR_HOST }}:{{ .SONARR_PORT }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
