---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "@daily"
        ttlSecondsAfterFinished: 86400

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: edge@sha256:1f5eab355cccc12b4c2f10d97c445ab00818e2afb06d227a8396aac29ad7930b

    command: ["/app/recyclarr/recyclarr"]
    args: ["sync"]

    envFrom:
      - secretRef:
          name: recyclarr-secret

    service:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        subPath: recyclarr.yml
        mountPath: /config/recyclarr.yml
        defaultMode: 0775
        readOnly: true
