---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secret-es
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .ESPHOME_WIFI_SSID }}"
          wifi_pwd: "{{ .ESPHOME_WIFI_PASSWORD }}"

          mqtt_host: "{{ .MQTT_EXTERNAL_HOST }}"
          mqtt_user: "{{ .ESPHOME_MQTT_USER }}"
          mqtt_pwd: "{{ .ESPHOME_MQTT_PASS }}"

          domain_devices: "{{ .MQTT_DEVICE_DOMAIN }}"
  dataFrom:
    - extract:
        key: esphome
    - extract:
        key: mqtt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-deploykey-es
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: esphome
        property: ESPHOME_DEPLOY_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-code-deploykey-es
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-code-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_rsa
      remoteRef:
        key: esphome
        property: ESPHOME_CODE_DEPLOY_KEY
