apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./netattach.yaml
  - ./pvc.yaml
  # - ./volsync.yaml
labels:
  - pairs:
      app.kubernetes.io/name: esphome
      app.kubernetes.io/instance: esphome
