---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY }}"
        MQTT_USER: "{{ .ZIGBEE2MQTT_EMQX_USER }}"
        MQTT_PASS: "{{ .ZIGBEE2MQTT_EMQX_PASS }}"
  dataFrom:
    - extract:
        # ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID, ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
        key: zigbee2mqtt
