---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  # - ./nodefeaturerule.yaml
  - ./pvc.yaml
  # - ./volsync.yaml
patchesStrategicMerge:
  - ./patches/env.yaml
  - ./patches/exporter.yaml
