---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app calibre
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: 6.14.1

    env:
      TZ: "${TIMEZONE}"
      PUID: "1111"
      PGID: "1111"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-pvc
        mountPath: /config
      books:
        enabled: true
        existingClaim: calibre-nfs-pvc
        mountPath: /nfs/media
      ingress:
        enabled: true
        existingClaim: calibre-ingress-nfs-pvc
        mountPath: /nfs/ingress

    service:
      main:
        ports:
          http:
            port: 8080
      content-server:
        enabled: true
        ports:
          content-server:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: ClusterIP

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # auth.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:bookshelf
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      content-server:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: book-open-page-variant
        hosts:
          - host: &host2 ccs.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: calibre-content-server
                  port: 8081
        tls:
          - hosts:
              - *host2
    resources:
      requests:
        cpu: 15m
        memory: 324M
      limits:
        memory: 604M
