apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./volsync.yaml
patchesStrategicMerge:
  - ./patches/postgres.yaml
labels:
  - pairs:
      app.kubernetes.io/name: calibre
      app.kubernetes.io/instance: calibre
