apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-nfs
spec:
  storageClassName: calibre-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: pelican.grz.bear
    path: /mnt/ingot/hydra/media/documents/books
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-nfs-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name calibre
    app.kubernetes.io/instance: *name
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: calibre-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-ingress-nfs
spec:
  storageClassName: calibre-ingress-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: pelican.grz.bear
    path: /mnt/ingot/hydra/swap/ingress/seedbox/books
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-ingress-nfs-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name calibre
    app.kubernetes.io/instance: *name
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: calibre-ingress-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name calibre
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
