---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ytdl-material-mongo-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ytdl-material-mongo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MONGO_USERNAME: "{{ .YTDL_MATERIAL_MONGO_USER }}"
        MONGO_PASSWORD: "{{ .YTDL_MATERIAL_MONGO_PASS }}"
  dataFrom:
    - extract:
        key: ytdl-material
