---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nocodb-es
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nocodb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # NOCODB
        NOCODB_JWT_SECRET: "{{ .NC_JWT_SECRET }}"
        NOCODB_ADMIN_EMAIL: "{{ .NC_ADMIN_EMAIL }}"
        NOCODB_ADMIN_PASS: "{{ .NC_ADMIN_PASS }}"
        NOCODB_REDIS_URL: "redis://{{ .REDIS_LB_HOST }}:{{ .REDIS_PORT }}/{{ .REDIS_NOCODB_DB }}"
        NOCODB_POSTGRES_URL: "postgresql://{{ .NC_PG_USER }}:{{ .NC_PG_PASS }}@{{ .PG_RW_INTERNAL_HOST }}/{{ .NC_PG_DB }}"
        NOCODB_SMTP_FROM: "NocoDB <{{ .EXTERNAL_SMTP_FROM_EMAIL }}>"
        # Postgres Init
        POSTGRES_DB: "{{ .NC_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .NC_PG_PASS }}"
        POSTGRES_USER: "{{ .NC_PG_USER }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        # Redis
        REDIS_HOST: "{{ .REDIS_LB_HOST }}"
        REDIS_PORT: "{{ .REDIS_LB_PORT }}"
        REDIS_DB: "{{ .REDIS_NOCODB_DB }}"
  dataFrom:
    - extract:
        key: nocodb
    - extract:
        key: cloudnative-pg
    - extract:
        key: external-smtp
    - extract:
        key: redis
