---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nocodb
  namespace: default
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: nocodb/nocodb
      tag: 0.98.2
    service:
      main:
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:database-eye
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host "noco.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: nocodb-data
        mountPath: /usr/app/data

    env:
      DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: NOCODB_POSTGRES_URL
      NC_AUTH_JWT_SECRET:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: NOCODB_JWT_SECRET
      NC_REDIS_URL:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: NOCODB_REDIS_URL
      NC_ADMIN_EMAIL:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: NOCODB_ADMIN_EMAIL
      NC_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: NOCODB_ADMIN_PASS
      NC_PUBLIC_URL: "https://noco.${SECRET_DOMAIN}"
      NC_INVITE_ONLY_SIGNUP: true
      NC_SMTP_HOST:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: SMTP_HOST
      NC_SMTP_FROM:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: NOCODB_SMTP_FROM
      NC_SMTP_PORT:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: SMTP_PORT
      NC_SMTP_USERNAME:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: SMTP_USER
      NC_SMTP_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nocodb-secret
            key: SMTP_PASS

    # redis:
    #   enabled: true
    # postgresql:
    #   enabled: true
    #   persistence:
    #     enabled: true
