---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./volsync.yaml
patchesStrategicMerge:
  - ./patches/postgres.yaml
labels:
  - pairs:
      app.kubernetes.io/name: &app nocodb
      app.kubernetes.io/instance: *app
