---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: &name nocodb
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 5Gi
