---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nocodb-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nocodb-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/nocodb'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .RESTIC_AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .RESTIC_AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nocodb
  namespace: default
spec:
  sourcePVC: nocodb-pvc
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: nocodb-restic-secret
    cacheCapacity: 10Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-filesystem
    retain:
      daily: 10
      within: 3d
