---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-es
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        # Postgres Init
        POSTGRES_DB: "{{ .AUTHENTIK_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_PORT: "{{ .PG_PORT }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .AUTHENTIK_PG_USER }}"
        POSTGRES_PASS: "{{ .AUTHENTIK_PG_PASS }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        SMTP_FROM: "Authentik {{ .EXTERNAL_SMTP_FROM_EMAIL }}"
        # GEOLITE
        GEOIP_ACCOUNT_ID: "{{ .GEOIP_ACCOUNT_ID }}"
        GEOLITE_LICENSE_KEY: "{{ .GEOLITE_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
    - extract:
        key: external-smtp
    - extract:
        key: geolite
