---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-discord
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flux-discord-secret
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: flux
        property: FLUX_DISCORD_WEBHOOK_URL
