---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wikijs-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wikijs-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres Init
        POSTGRES_DB: "{{ .WIKIJS_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_PORT: "{{ .PG_PORT }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .WIKIJS_PG_USER }}"
        POSTGRES_PASS: "{{ .WIKIJS_PG_PASS }}"
  dataFrom:
    - extract:
        key: wikijs
    - extract:
        key: cloudnative-pg
