---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cert-manager-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # cloudflare
        api-key: "{{ .CF_API_KEY }}"
  dataFrom:
    - extract:
        key: cloudflare
