apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:J0GBnLlPu2IlY2jDSkLeFdDAZdoLdcaRPN6zvfrb7ttYajzrSw==,iv:0Sut93mNymqanyGAeEWzdD1euKYoxFMpsbSCjUR/1b0=,tag:c83ZqOPdiWGr7sebT3RUuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMFFGVTZkdjRhby9LVW43
            ek5raE5NRGFocUZhWGNLcVNaaENFc2prbHc4ClJRdWJVb1Y0MTRHL29tbXBkVDVt
            emNKL2p0QWdIb2w2V1JDY2FWaVZlSVEKLS0tIENrQlNsbXp4cGtmNnpCZzRIQzNY
            a2gzNE5mTGxJRFNNMzBpV1VPblFQYzQK//pRcqlLpedgPxm0kxbJhRmK3GXcvHZ4
            d6VRYAnEftwFRKkmw9XRggBHLltWnZADzyzJBgUHqcy8RPRyLi6NpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T11:54:45Z"
    mac: ENC[AES256_GCM,data:rrT+Mz/IIk5DooiEsrPDqgLloJDPGuoTGjGUmLnREJpenKGy3umyS1JQviWcRfEdUdpiGUpWcunEOc8zTkOq2v1nhP0B6GHdm9K/lPTYUEAg8h7R1p7Vzj8YupEkYYlm/19gncieGZlrDWcWEl9fv0RkMlKFFpX7NkYg4Tb1MBU=,iv:Ms3jW6A3mJjD0RNHfa4+fG4PbUhCqErQO7BkkpLzp/E=,tag:ciZc/O+yF7lUYWsuCMCWGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
