---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # cloudflare
        email: "{{ .CF_EMAIL }}"
        api-key: "{{ .CF_API_KEY }}"
  dataFrom:
    - extract:
        key: cloudflare
