apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:naITI+FskpMCDQQ+plxuKhtuN52TrrqyjQ==,iv:GkjbmM9+tTBn/IS/fElGskVBMowgzZ13Ix7O7ikozdA=,tag:TPJlzkAauO4YXUe9P3O6IA==,type:str]
    api-key: ENC[AES256_GCM,data:NbvKG9pRZD4YWlSWhbk7u4to4KYd9aVeRiNyLdncvlJuFIpObw==,iv:2ur+vSHBWZBATFyhcHefgF0NI3SE09hpWAHDWHoXhuA=,tag:DPjNmSdCiJTRQh9OlBTxpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEenJ2QVZlRllQREhiNE9i
            TktBNmpEVytYZzNlU3ZrTXZxYW9YelV0aUZnCitXcjFUTnlNT2NnZXJsZ3k3UmU1
            b1dIK2UvQndFWGJWQUdvUWZGWnZDeTQKLS0tIHRLV1hobzRCbTBEcCtvSGtRUHJi
            SHQ2SFRMWXFMc3lqZmF3ZlVGVzlDMEkKwLFuqSFVtNP7UPS/jh48lzH29nJv6X9r
            lpTjpYGd0gk5C3Uvk8yADpWCn1j8GddkNJtd6GqV2Xj6SGtS3rYC+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T00:34:17Z"
    mac: ENC[AES256_GCM,data:UHUkBcj5adMGyTpymSZ8X794GMOuOAQde/EA5QpOHSCehsP1YqSBeTaNKl7P9wprQxvGT/bvdBqNdxHV44hH+SMYJ3i54DmEUU3GcQ3rzNUfJ9CZMa4B//eXpJNiD0HfRG8nyfYsJNHHMy0ZndRYaJ84gb2r6f7HqSWB7gHKnOU=,iv:/QtxoqxqpERRT5licVKI2w2oNAqkbpZwaLqZXLQFkGc=,tag:YL+XXgLO5TUKAI398MRG1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
