---
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.storage.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.storage.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.storage.svc.cluster.local
          port: 26379

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    # - domain: ["grafana.${SECRET_DOMAIN}"]
    #   policy: bypass
        # bypass Authelia WAN + LAN
    - domain:
        - auth.${SECRET_DOMAIN}
      policy: bypass
    # One factor auth for LAN
    - domain:
        - "*.${SECRET_DOMAIN}"
      policy: one_factor
      subject: ["group:admins", "group:users"]
      networks:
        - internal
    # - domain: ["navidrome.${SECRET_DOMAIN}"]
    #   resources: ["^/rest.*$"]
    #   policy: bypass
    # - domain: ["navidrome.${SECRET_DOMAIN}"]
    #   resources: ["^/metrics.*$"]
    #   policy: deny
    # - domain: ["wizarr.${SECRET_DOMAIN}"]
    #   resources: ["^/join.*$", "^/j/.*$", "^/setup.*$", "^/static/.*$"]
    #   policy: bypass

identity_providers:
  oidc:
    enable_client_debug_messages: true
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret:
          valueFrom:
            secretKeyRef:
              name: authelia-secret
              key: GRAFANA_OAUTH_CLIENT_SECRET
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signing_algorithm: none
#       - id: immich
#         description: Immich
#         secret: "${IMMICH_OAUTH_CLIENT_SECRET}"
#         public: false
#         authorization_policy: two_factor
#         pre_configured_consent_duration: 1y
#         scopes: ["openid", "profile", "email"]
#         redirect_uris: ["https://photos.${SECRET_DOMAIN}/auth/login", "app.immich:/"]
#         userinfo_signing_algorithm: none
#       - id: miniflux
#         description: Miniflux
#         secret: "${MINIFLUX_OAUTH_CLIENT_SECRET}"
#         public: false
#         authorization_policy: two_factor
#         pre_configured_consent_duration: 1y
#         scopes: ["openid", "profile", "groups", "email"]
#         redirect_uris: ["https://miniflux.${SECRET_DOMAIN}/oauth2/oidc/callback"]
#         userinfo_signing_algorithm: none
      - id: weave-gitops
        description: Weave GitOps
        secret:
          valueFrom:
            secretKeyRef:
              name: authelia-secret
              key: WEAVEGITOPS_OAUTH_CLIENT_SECRET
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://gitops.${SECRET_DOMAIN}/oauth2/callback"]
        userinfo_signing_algorithm: none
