---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-postgres-s3
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-postgres-s3
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: minio
        property: MINIO_HOME_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: minio
        property: MINIO_HOME_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-postgres-superuser
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-postgres-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative-pg-postgres-superuser
        property: superuser_username
    - secretKey: password
      remoteRef:
        key: cloudnative-pg-postgres-superuser
        property: superuser_password
