---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ytdl-material-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ytdl-material-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MONGO_CONNECTION: "mongodb://{{ .YTDL_MATERIAL_MONGO_USER }}:{{ .YTDL_MATERIAL_MONGO_PASS }}@{{ .YTDL_MATERIAL_MONGO_HOST }}:{{ .YTDL_MATERIAL_MONGO_PORT }}"
  dataFrom:
    - extract:
        key: ytdl-material
