# https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/docker-compose.yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ytdl-material
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: ghcr.io/tzahi12345/youtubedl-material
      tag: nightly-2023-01-31
    env:
      TZ: "${TIMEZONE}"
      UID: "${SECRET_NFS_2_UID}"
      GID: "${SECRET_NFS_2_GID}"
      ytdl_use_local_db: "false"
      write_ytdl_config: "true"
      ytdl_mongodb_connection_string:
        valueFrom:
          secretKeyRef:
            name: &secret ytdl-material-secret
            key: MONGO_CONNECTION
    persistence:
      data:
        enabled: true
        existingClaim: ytdl-material-nfs-pvc
        subPath:
          - path: data
            mountPath: /app/appdata
          - path: audio
            mountPath: /app/audio
          - path: video
            mountPath: /app/video
          - path: subscriptions
            mountPath: /app/subscriptions
          - path: users
            mountPath: /app/users

    podAnnotations:
      secret.reloader.stakater.com/reload: *secret

    service:
      main:
        ports:
          http:
            port: 17442
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: youtube
        hosts:
          - host: &host "ytdl.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
