apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./pvc.yaml
labels:
  - pairs:
      app.kubernetes.io/name: ytdl-material
      app.kubernetes.io/instance: ytdl-material
