---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./gitea/ks.yaml
  - ./hajimari/ks.yaml
  - ./nocodb/ks.yaml
  - ./shlink/ks.yaml
  - ./uptime-kuma/ks.yaml
  - ./vikunja/ks.yaml
