---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.1.3.2464@sha256:990932de9d6338842f10b8ac00041d02257b5593c151c019072a297e6f6991f4
    env:
      TZ: ${TIMEZONE}
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 80
      PROWLARR__LOG_LEVEL: info
      PROWLARR__AUTHENTICATION_METHOD: External
    envFrom:
      - secretRef:
          name: prowlarr-secret
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/icon: mdi:movie-search
          hajimari.io/enable: "true"
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
        - 10000
        - 65542

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: prowlarr-config-pvc

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
