---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name ombi
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
