---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: photoprism-es
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: photoprism-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_PASS: "{{ .PHOTOPRISM_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: photoprism
