---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    image:
      repository: docker.io/photoprism/photoprism
      tag: latest@sha256:16645a56a968e9411a0b432a84887d8e2a77e8bdab96aa1d6b8654132b1797c8

    env:
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      ## See other config options from PhotoPrism documentation: https://docs.photoprism.org/getting-started/config-options/
      PHOTOPRISM_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: photoprism-secret
            key: ADMIN_PASS   # Initial admin password: PLEASE CHANGE!
      # PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      # PHOTOPRISM_PUBLIC: "true"                     # No authentication required (disables password protection)
      # PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      # PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
      PHOTOPRISM_SITE_URL: "https://photos.${SECRET_DOMAIN}/"  # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "Photoprism"
      PHOTOPRISM_SITE_CAPTION: "Casa"
      # PHOTOPRISM_SITE_DESCRIPTION: "una descripcion"
      # PHOTOPRISM_SITE_AUTHOR: ""
      # # You may optionally set user, group and/or file permissions using environment variables:
      UID: 33
      GID: 33
      # UMASK: 0000
      PHOTOPRISM_ORIGINALS_LIMIT: 4000 # in MB (default 1000)

    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        existingClaim: photoprism-storage-nfs-pvc

      originals:
        enabled: true
        mountPath: "/photoprism/originals"
        existingClaim: photoprism-originals-nfs-pvc


    service:
      main:
        ports:
          http:
            port: 2342

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: arcticons:photoprism
          hajimari.io/info: Manage Photos
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
        hosts:
          - host: &host photos.${SECRET_DOMAIN}
            paths:
              - path: /
                # Ignored if not kubeVersion >= 1.14-0
                pathType: Prefix
        tls:
          - hosts:
              - *host
