---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kutt
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kutt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Kutt
        KUTT_POSTGRES_URL: "postgresql://{{ .KUTT_PG_USER }}:{{ .KUTT_PG_PASS }}@{{ .PG_RW_INTERNAL_HOST }}/{{ .KUTT_PG_DB }}"
        KUTT_ADMIN_EMAILS: "{{ .KUTT_ADMIN_EMAILS }}"
        KUTT_REPORT_EMAIL: "{{ .KUTT_REPORT_EMAIL }}"
        KUTT_CONTACT_EMAIL: "{{ .KUTT_CONTACT_EMAIL }}"
        JWT_SECRET: "{{ .KUTT_JWT_SECRET }}"
        # Redis
        REDIS_HOST: "{{ .REDIS_LB_HOST }}"
        REDIS_PORT: "{{ .REDIS_PORT }}"
        REDIS_DB: "{{ .REDIS_KUTT_DB }}"
        # Postgres Init
        POSTGRES_DB: "{{ .KUTT_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .KUTT_PG_PASS }}"
        POSTGRES_USER: "{{ .KUTT_PG_USER }}"
        # SMTP
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        SMTP_FROM: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
        SMTP_SECURE: "{{ .EXTERNAL_SMTP_SECURE }}"
  dataFrom:
    - extract:
        key: kutt
    - extract:
        key: cloudnative-pg
    - extract:
        key: redis
    - extract:
        key: external-smtp
