---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kutt
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    global:
      nameOverride: *app

    image:
      repository: kutt/kutt
      tag: 2.4.7

    service:
      main:
        ports:
          http:
            port: &port 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: mdi:sword
        hosts:
          - host: &host "kutt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    env:
      # App port to run on
      PORT: *port

      # The name of the site where Kutt is hosted
      SITE_NAME: Kutt

      # The domain that this website is on
      DEFAULT_DOMAIN: *host

      # Generated link length
      LINK_LENGTH: 6

      # Postgres database credential details
      DB_HOST:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: POSTGRES_HOST
      DB_PORT: 5432
      DB_NAME:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: POSTGRES_DB
      DB_USER:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: POSTGRES_USER
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: POSTGRES_PASS
      DB_SSL: false

      # Redis host and port
      REDIS_HOST:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: REDIS_HOST
      REDIS_PORT:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: REDIS_PORT
      # REDIS_PASSWORD:
      REDIS_DB:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: REDIS_DB

      # Disable registration
      DISALLOW_REGISTRATION: false

      # Disable anonymous link creation
      DISALLOW_ANONYMOUS_LINKS: true

      # The daily limit for each user
      USER_LIMIT_PER_DAY: 50

      # Create a cooldown for non-logged in users in minutes
      # Set 0 to disable
      NON_USER_COOLDOWN: 0

      # Max number of visits for each link to have detailed stats
      DEFAULT_MAX_STATS_PER_LINK: 5000

      # Use HTTPS for links with custom domain
      CUSTOM_DOMAIN_USE_HTTPS: false

      # A passphrase to encrypt JWT. Use a long and secure key.
      JWT_SECRET:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: JWT_SECRET

      # Admin emails so they can access admin actions on settings page
      # Comma seperated
      ADMIN_EMAILS:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: KUTT_ADMIN_EMAILS

      # Invisible reCaptcha secret key
      # Create one in https://www.google.com/recaptcha/intro/
      # RECAPTCHA_SITE_KEY:
      # RECAPTCHA_SECRET_KEY:

      # Google Cloud API to prevent from users from submitting malware URLs.
      # Get it from https://developers.google.com/safe-browsing/v4/get-started
      # GOOGLE_SAFE_BROWSING_KEY:

      # Your email host details to use to send verification emails.
      # More info on http://nodemailer.com/
      # Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
      MAIL_HOST:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: SMTP_HOST
      MAIL_PORT:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: SMTP_PORT
      MAIL_SECURE:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: SMTP_SECURE
      MAIL_USER:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: SMTP_USER
      MAIL_FROM:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: SMTP_FROM
      MAIL_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: SMTP_PASS

      # The email address that will receive submitted reports.
      REPORT_EMAIL:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: KUTT_REPORT_EMAIL

      # Support email to show on the app
      CONTACT_EMAIL:
        valueFrom:
          secretKeyRef:
            name: kutt-secret
            key: KUTT_CONTACT_EMAIL
