---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: '{{ .RADARR_PUSHOVER_TOKEN }}'
        PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY }}'
        RADARR__API_KEY: '{{ .RADARR_API_KEY }}'
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, SONARR__API_KEY
        key: radarr
    - extract:
        # PUSHOVER_USER_KEY
        key: pushover
