---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # outline
        OL_DB_USER: &dbuser "{{ .OL_DB_USER }}"
        OL_DB_PASS: &dbpass "{{ .OL_DB_PASS }}"
        OL_DB_HOST: &dbhost "{{ .PG_RW_INTERNAL_HOST }}"
        OL_DB_NAME: &dbname outline
        OL_DB_SSL_MODE: disable
        OL_DB_TYPE: postgres
        OL_S3_BUCKET: "{{ .OL_S3_BUCKET }}"
        DATABASE_URL: "postgres://{{ .OL_DB_USER }}:{{ .OL_DB_PASS }}@{{ .PG_RW_INTERNAL_HOST }}:5432/outline"
        SECRET_KEY: "{{ .OL_SECRET_KEY }}"
        UTILS_SECRET: "{{ .OL_UTILS_SECRET }}"
        # minio
        MINIO_S3_REGION: "{{ .MINIO_S3_REGION }}"
        MINIO_HOME_ACCESS_KEY: "{{ .MINIO_HOME_ACCESS_KEY }}"
        MINIO_HOME_SECRET_KEY: "{{ .MINIO_HOME_SECRET_KEY }}"
        # authelia
        OUTLINE_OAUTH_CLIENT_SECRET: "{{ .OUTLINE_OAUTH_CLIENT_SECRET }}"
        # smtp
        EXTERNAL_SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        EXTERNAL_SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        EXTERNAL_SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        EXTERNAL_SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        EXTERNAL_SMTP_FROM_EMAIL: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
        # Postgres Init
        POSTGRES_DB: *dbname
        POSTGRES_HOST: *dbhost
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: *dbpass
        POSTGRES_USER: *dbuser
  dataFrom:
    - extract:
        key: outline
    - extract:
        key: cloudnative-pg
    - extract:
        key: authelia
    - extract:
        key: minio
    - extract:
        key: external-smtp
