---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # outline
        OL_DATABASE_USER: "{{ .OL_DATABASE_USER }}"
        OL_DATABASE_PASSWORD: "{{ .OL_DATABASE_PASSWORD }}"
        OL_DATABASE_HOST: &dbhost "{{ .PG_RW_INTERNAL_HOST }}"
        OL_DATABASE_NAME: &dbname outline
        OL_DATABASE_SSL_MODE: disable
        OL_DATABASE_TYPE: postgres
        # minio
        MINIO_S3_REGION: "{{ .MINIO_S3_REGION }}"
        # authelia
        OUTLINE_OAUTH_CLIENT_SECRET: "{{ .OUTLINE_OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        POSTGRES_DB: *dbname
        POSTGRES_HOST: postgres-rw.storage.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .OL_DATABASE_PASSWORD }}"
        POSTGRES_USER: "{{ .OL_DATABASE_USER }}"
  dataFrom:
    - extract:
        key: outline
    - extract:
        key: cloudnative-pg
    - extract:
        key: authelia
    - extract:
        key: minio
