apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-services
resources:
  - ./endpoints.yaml
  - ./service.yaml
  - ./ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: plex
      app.kubernetes.io/instance: plex
