---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: home-ops
  namespace: actions-runner-system
spec:
  template:
    spec:
      image: ghcr.io/actions/actions-runner-controller/actions-runner-dind:v2.299.1-ubuntu-22.04
      imagePullPolicy: IfNotPresent
      dockerdWithinRunnerContainer: true
      ephemeral: true
      repository: benwalio/home-ops
      labels: ["self-hosted"]
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: actions-runner-controller-cache
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: home-ops
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: home-ops
  scaleUpTriggers:
    - githubEvent:
        checkRun:
          types: ["created"]
          status: "queued"
      amount: 1
      duration: 1m
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - benwalio/home-ops
