---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: storage
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6
  primaryUpdateStrategy: unsupervised
  storage:
    size: 40Gi
    storageClass: ceph-block

  affinity:
    nodeSelector:
      node.benwal.casa/instance-type: "bare-metal"

  superuserSecret:
    name: cloudnative-pg-superuser
  # bootstrap:
  #   recovery:
  #     source: &active-cluster postgres-v2
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: http://minio.storage.svc.cluster.local:9000
      serverName: postgres-v3
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-s3
          key: S3_ACCESS_KEY
        secretAccessKey:
          name: cloudnative-pg-s3
          key: S3_SECRET_KEY
  # externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *active-cluster
  #     barmanObjectStore:
  #       wal:
  #         compression: bzip2
  #         maxParallel: 8
  #       destinationPath: s3://postgresql/
  #       endpointURL: http://minio.storage.svc.cluster.local:9000
  #       s3Credentials:
  #         accessKeyId:
  #           name: cloudnative-pg-s3
  #           key: S3_ACCESS_KEY
  #         secretAccessKey:
  #           name: cloudnative-pg-s3
  #           key: S3_SECRET_KEY
