---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./scheduledbackup.yaml
labels:
  - pairs:
      app.kubernetes.io/name: &app cloudnative-pg-cluster
      app.kubernetes.io/instance: *app
      app.kubernetes.io/part-of: cloudnative-pg
