---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      tag: 8.8.6
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${SVC_ZWAVE_JS_ADDR}
        # annotations:
        #   metallb.universe.tf/loadBalancerIPs: "${SVC_ZWAVE_JS_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: &port 8091
          websocket:
            port: 3000

    serviceMonitor:
      main:
        enabled: true
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:z-wave
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      privileged: true
    # volumeClaimTemplates:
    #   - name: config
    #     mountPath: /usr/src/app/store
    #     accessMode: ReadWriteOnce
    #     size: 1Gi
    #     storageClass: ceph-block
    #     labels:
    #       snapshot.home.arpa/enabled: "true"
    persistence:
      config:
        enabled: true
        existingClaim: zwave-js-ui-pvc
        mountPath: /usr/src/app/store
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_fea810d17d58ea119da1602b5af1e32e-if00-port0 #TODO: figure this shiz out
        hostPathType: CharDevice
    nodeSelector:
      slabs.feature.node.kubernetes.io/zwave: "true"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
