---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: silicon-labs-zwave-device
spec:
  rules:
    - # Silicon Labs Z-Stick
      name: silicon-labs.zwave
      labels:
        slabs.feature.node.kubernetes.io/zwave: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["ff"] }
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }
