---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-ui-pvc
  namespace: home-automation
  labels:
    app.kubernetes.io/name: &name zwave-js-ui
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
