---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.3.1@sha256:840242bb1dfb337e5bfa579af039738bbf9948f6f33deecf451ebdd9ca509e31
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   proxy_set_header Accept-Encoding "";
          #   sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.devbu.io/css/base/bazarr/nord.css"></head>';
          #   sub_filter_once on;
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/icon: mdi:subtitles-outline
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1111
      runAsGroup: 1111
      fsGroup: 1111
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 1100

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: bazarr-config-pvc
      tv:
        enabled: true
        existingClaim: bazarr-tv-nfs-pvc
        mountPath: /nfs/tv
      movie:
        enabled: true
        existingClaim: bazarr-movie-nfs-pvc
        mountPath: /nfs/movie
      add-ons:
        enabled: true
        type: emptyDir
        mountPath: /add-ons

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
    sidecars:
      subcleaner:
        image: registry.k8s.io/git-sync/git-sync:v3.6.4
        imagePullPolicy: IfNotPresent
        args:
          - --repo=https://github.com/KBlixt/subcleaner.git
          - --branch=master
          - --depth=1
          - --wait=21600 # 6 hours
          - --root=/add-ons/subcleaner
        volumeMounts:
          - { name: add-ons, mountPath: /add-ons }
