apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:zBwCgwkvtVddK3X6cm6C0+wpHTR8t7tft+eAH/86U2HsszR/0VqILrFn1yP6vObJUsib67iGwRuqNx5Q,iv:FTrX4n1oNFjfPr5HDtEZbVZ6U+Q9OXCP7nTCQrY0y4M=,tag:FQuikdkhgXLYvT2ex+sI0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WXZXQW1aUTJDUTl2L2xl
            R0hMeVNjNTRvcStnVlM2V1pySERaOXpxR1JnCmVoei9XUTdFdTExdjhCRm0rMmxV
            N1VhNHVjdmk0REkwTE1hcGtVUFJPd1EKLS0tIFRaQy9WZTVuaGh3NG9CNjQvZ2hy
            dGl4c3UrMENZUEszR0NMb0pRcFZQcU0KcjmGC2C3KDd9tZ8V3ZSha6GUMSCjwS6O
            4nfNfu25jsQwC2c3FEOrBSeScXTCILOBy74sPHp7RD1cKDnutsIbVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T00:11:27Z"
    mac: ENC[AES256_GCM,data:nh78eRHpW7ejsvcJe6v3vW4IafJxsriX8dLEQ1F+vOJ1bj71gLYwkwV8ghUAJckzHF4qO6PWZjNvSPlIVeIYu+EtOVK8OkjcpQArtL+YOLpWb8i7J278wO5TevusS588r6IMQvKc4DSNFsuus/6pXYC9K56vPd+ZuQWiMB8hNeE=,iv:nuHVd4uKta9OFc61hPO3JPhTmwIVzhWTlh+w9pqG91U=,tag:zakpMmHwDUiMIZnGlcrDyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
