apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:uBb98pOm7RpruqwcxVSX+RVCmYkHHwtjHCIX4QHDT0Kh0W88JW6+jgJoqv7cpeg1mFvchAanHgTs9OFh,iv:yt6PnbGDj741ICKadFaqJtOxF06xxFHhF45nFYWeI1c=,tag:YTiuUPY714lOLKvK77BYrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU3lJSEFRMjZIcHdqSjV4
            YWdRdHROVlkyQXNNU1MxRHJlUVRrTURoMENzCnRKaTVsWktyRVB1dGFQZ0gvRTVj
            d2lCSTRIdUVFdnJGeGVSa0lTc2lVeTQKLS0tIFR6YlBHa29hRXdBWm5Oemx3WmJ1
            RS82UnJxeUxMMUw0MWNLaDlld2ZwcGsKGAdYRlf62+M9e090ol0DXrZvLo7IUY2e
            7xDtgCWG2HsuCTtJLtAvafTkbKTo/KYj9j6O/jFMwmSVaDFm1U3m8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T01:53:23Z"
    mac: ENC[AES256_GCM,data:eNh0FgMNgVK3Zb4w6bnSpLGoEtAp+EI2jzE5JbvejIx3u2PYto0KmQLGYhBldHYY9S/z28vWhZMi/5B0rQMGI9dnAR3eF7LRanKasfTQhVjjn21ekEDGrO1RCvVTziKas2WW0CgVY2ROBreiazdMPd/P73306IAGOZNSFu9uW0w=,iv:fal97sz6l/PLbucEBcw3sJMF96ktecui+vFER59hx5A=,tag:GAHSfPWt9IJFaV1bYIDZNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
