apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:EbSO957NhUxaDsGSOSbHRYW34JA5FBAXA5pHt0IsmA732bh6l7YK/aPs5xxNzf1AD3i2+L8WVWAF8cbu,iv:Fl7gluSOalsKMv6XoUIkqYLUDXEULU9+4X5RJkXsINw=,tag:goR1M9Wu8ocpDJ8+eCM2GA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTFM0UG9Mb29EZXhSYjRi
            L2xyV3I4T3NUK3plYXVGZ1NSWnh4OCtSK0RrClBzYU1CK2FVaUlhSmNqRVdHR1VV
            S3dxckFzOFFuUERFR3JyWk52N05hMUkKLS0tIHI3WHUxMlV0dVo4eXlIYXpyWk9O
            bWRlQjhSTVBsdW5GMUMwOE9ZdnQvWmcKdw1EIdH/Y87XTYXzJvNUZSOQ4TuUchPx
            M+8g+ut27Bem2piZbdthYQ35XjrjRRdrpBgRoPRSPULRLBiGKHWc+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T11:44:17Z"
    mac: ENC[AES256_GCM,data:WpUzTpYsSxPCgAylV4QvDNib14e+UsIKrmQIc87ikaYcMBLNTDvWZ0Fa3VWJpJxvlxXpRcV/96xpZkCnFgovzlqk4GfKCERSXsqI3swt7GNkwfUb5eeNS2B3KaRHkZCmixmxIlO1+5oGbZxddTe9jb/Ka0/TMZtN856dU9vtGKs=,iv:Ve2baiVFD1Uw1qVmIKZXTdviUl0pkTQbTdDkrbSUvg8=,tag:26e41/p5cSIdi7K2UCGhTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
