---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud
  namespace: external-services
subsets:
  - addresses:
      - ip: 10.69.10.11
    ports:
      - name: http
        port: 9001
        protocol: TCP
