---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.69.10.201"
  METALLB_LB_RANGE: "10.69.10.151-10.69.10.200"
  METALLB_K8S_GATEWAY_ADDR: "10.69.10.199"
  METALLB_INGRESS_ADDR: "10.69.10.200"
