---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.69.10.69"
  METALLB_LB_RANGE: "10.69.10.70-10.69.10.100"
  METALLB_K8S_GATEWAY_ADDR: "10.69.10.99"
  METALLB_INGRESS_ADDR: "10.69.10.100"

  METALLB_DNS_ADDR: "10.69.10.98"
