---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: networking-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/kubernetes/apps/networking"
