---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadOnlyMany"]
  storageClassName: plex-media-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.9
    path: /volume1/media
  mountOptions: ["nfsvers=4.1"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-nfs-pvc
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: plex-media-nfs
  resources:
    requests:
      storage: 1Mi
