---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-es
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: "{{ .LOKI_S3_BUCKET }}"
        S3_BUCKET_HOST: "{{ .MINIO_ENDPOINT }}"
        S3_BUCKET_REGION: "{{ .MINIO_S3_REGION }}"
        S3_ACCESS_KEY: "{{ .LOKI_S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .LOKI_S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: loki
    - extract:
        key: minio
