---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  # - ./op-loki-secret.yaml
  - ./configmap.yaml
  - ./objectbucketclaim.yaml
  - ./helmrelease.yaml
