---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-gotenberg
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      strategy: RollingUpdate
    image:
      # https://hub.docker.com/r/gotenberg/gotenberg
      repository: docker.io/gotenberg/gotenberg
      tag: 7.8.1
    command: [gotenberg]
    args: [--chromium-disable-routes=true]
    service:
      main:
        ports:
          http:
            port: 3000
