---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-audio-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-audio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        READARR_AUDIO_API_KEY: "{{ .READARR_AUDIO_API_KEY }}"
  dataFrom:
    - extract:
        key: readarr
