---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_POSTGRES_URL: "postgresql://{{ .HASS_PG_USER }}:{{ .HASS_PG_PASS }}@{{ .PG_RW_INTERNAL_HOST }}/{{ .HASS_PG_DB }}"
        # Postgres Init
        POSTGRES_DB: "{{ .HASS_PG_DB }}"
        POSTGRES_HOST: "{{ .PG_RW_INTERNAL_HOST }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .HASS_PG_PASS }}"
        POSTGRES_USER: "{{ .HASS_PG_USER }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: cloudnative-pg
