---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cloudnative-pg
      namespace: storage
    - name: emqx
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        envFrom:
          - secretRef:
              name: home-assistant-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.2.3@sha256:4dec60ce9a1cebbd2397142d0324e2cd762331f1c0cb447fd7c80ead17190e17

    podAnnotations:
      k8s.v1.cni.cncf.io/networks: macvlan-static-iot-hass, macvlan-static-lan-hass

    env:
      TZ: ${TIMEZONE}
    envFrom:
      - secretRef:
          name: home-assistant-secret
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${SVC_HOME_ASSISTANT_ADDR}
        # annotations:
        #   metallb.universe.tf/loadBalancerIPs: "${SVC_HOME_ASSISTANT_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
          ssdp-tcp:
            enabled: true
            port: 1900
            protocol: TCP
            targetPort: 1900
          ssdp-udp:
            enabled: true
            port: 1900
            protocol: UDP
            targetPort: 1900

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:home-assistant
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host hass.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: home-assistant-tls

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-pvc
        mountPath: /config
    # volumeClaimTemplates:
    #   - name: config
    #     mountPath: /config
    #     accessMode: ReadWriteOnce
    #     size: 5Gi
    #     storageClass: ceph-block
    #     labels:
    #       snapshot.home.arpa/enabled: "true"

    nodeSelector:
      node-role.kubernetes.io/worker: "true"
      node.benwal.casa/instance-type: "bare-metal"

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
