---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cloudnative-pg
      namespace: storage
    - name: emqx
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        envFrom:
          - secretRef:
              name: home-assistant-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2022.12.8@sha256:7ee4d4e728ae3091a6537a8f6c73e9702609524fc59aa2614bf16744a5338054
    env:
      TZ: ${TIMEZONE}
    envFrom:
      - secretRef:
          name: home-assistant-secret
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${SVC_HOME_ASSISTANT_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host hass.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
