---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # - ./netattach.yaml
  - ./pvc.yaml
  # - ./volsync.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
