---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./nas-minio/ks.yaml
  - ./nextcloud/ks.yaml
  - ./paperless/ks.yaml
  - ./zigbee2mqtt/ks.yaml
