---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "${BOOTSTRAP_CLOUDFLARE_DOMAIN}"
  SECRET_CLOUDFLARE_EMAIL: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  SECRET_PUSHOVER_USER_KEY: "${BOOTSTRAP_SECRET_PUSHOVER_USER_KEY}"
  SECRET_PUSHOVER_ALERTMANAGER_APP_KEY: "${BOOTSTRAP_SECRET_PUSHOVER_ALERTMANAGER_APP_KEY}"
