---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Immich
        DB_DATABASE_NAME: &dbname "{{ .IMMICH_PG_DB }}"
        DB_HOSTNAME: &dbhost "{{ .PG_RW_INTERNAL_HOST }}"
        DB_USERNAME: &dbuser "{{ .IMMICH_PG_USER }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH_PG_PASS }}"
        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"
        # Postgres Init
        POSTGRES_DB: *dbname
        POSTGRES_HOST: *dbhost
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: *dbuser
        POSTGRES_PASS: *dbpass
        # Typesense
        TYPESENSE_API_KEY: "{{ .IMMICH_TYPESENSE_API_KEY }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
