---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    global:
      nameOverride: *app

    image:
      repository: louislam/uptime-kuma
      tag: 1.21.3

    service:
      main:
        ports:
          http:
            port: 3001

    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-pvc
        mountPath: /app/data

    # volumeClaimTemplates:
    #   - name: config
    #     mountPath: /app/data
    #     accessMode: ReadWriteOnce
    #     size: 5Gi
    #     storageClass: ceph-block
    #     labels:
    #       snapshot.home.arpa/enabled: "true"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: mdi:alert-circle-check
        hosts:
          - host: &host "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
