---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app calibre-web
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.20
    env:
      TZ: "${TIMEZONE}"
      # PUID: 1111
      # PGID: 1111
      # DOCKER_MODS: "linuxserver/mods:universal-calibre"
    service:
      main:
        ports:
          http:
            port: 8083
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   proxy_set_header Accept-Encoding "";
          #   sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/base/calibreweb/dracula.css"></head>';
          #   sub_filter_once on;
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
        hosts:
          - host: &host "books.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 1111
      runAsGroup: 1111
      fsGroup: 1111
      fsGroupChangePolicy: "OnRootMismatch"
      # supplementalGroups:
      #   - 1111
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-pvc
        mountPath: /config
      books:
        enabled: true
        existingClaim: calibre-web-nfs-pvc
        mountPath: /books
    resources:
      requests:
        memory: 256Mi
    probes:
      startup:
        spec:
          periodSeconds: 15
