---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "${BOOTSTRAP_TIMEZONE}"
  KUBE_VIP_ADDR: "${BOOTSTRAP_KUBE_VIP_ADDR}"
  METALLB_LB_RANGE: "${BOOTSTRAP_METALLB_LB_RANGE}"
  METALLB_K8S_GATEWAY_ADDR: "${BOOTSTRAP_METALLB_K8S_GATEWAY_ADDR}"
  METALLB_INGRESS_ADDR: "${BOOTSTRAP_METALLB_INGRESS_ADDR}"

  SVC_K8S_GATEWAY_ADDR: "${BOOTSTRAP_SVC_K8S_GATEWAY_ADDR}"
  SVC_ADGUARD_ADDR: "${BOOTSTRAP_SVC_ADGUARD_ADDRESS}"
  # SVC_HOME_ASSISTANT_ADDR: "${BOOTSTRAP_SVC_HOME_ASSISTANT_ADDR}"
  SVC_REDIS_ADDR: "${BOOTSTRAP_SVC_REDIS_ADDR}"
  SVC_PLEX_ADDR: "${BOOTSTRAP_SVC_PLEX_ADDR}"
  SVC_EMQX_ADDR: "${BOOTSTRAP_SVC_EMQX_ADDR}"
  # SVC_QBIT_ADDR: "${BOOTSTRAP_SVC_QBIT_ADDR}"
  SVC_SYSLOG_ADDR: "${BOOTSTRAP_SVC_SYSLOG_ADDR}"
  SVC_LDAP_ADDR: "${BOOTSTRAP_SVC_LDAP_ADDR}"
  # SVC_ZWAVE_JS_ADDR: "${BOOTSTRAP_SVC_ZWAVE_JS_ADDR}"
