---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-adguard
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-metallb
    - name: cluster-apps-metallb-config
  path: ./kubernetes/apps/networking/adguard/app
  prune: true
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: adguard-home
      namespace: networking
  interval: 15m
  retryInterval: 1m
  timeout: 3m
