---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./minio/ks.yaml
  - ./redis/ks.yaml
  - ./volsync/ks.yaml
